# -*- coding: utf-8 -*-
"""ListaTarefasIA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w3HkuG-tbqtO-WTUY8VjhHQRY973BinV
"""

class Acao:
    def __init__(self, nome, preconds, add, delete):
        #açao
        self.nome = nome
        #precondição
        self.preconds = set(preconds)
        self.add = set(add)
        self.delete = set(delete)

    def __repr__(self):
        return f"{self.nome}"

acoes_disney = [
    Acao("emitir_passaporte", ["sem_passaporte"], ["com_passaporte"], ["sem_passaporte"]),
    Acao("obter_visto", ["com_passaporte", "sem_visto"], ["com_visto"], ["sem_visto"]),
    Acao("comprar_passagens", ["sem_passagens"], ["com_passagens"], ["sem_passagens"]),
    Acao("reservar_hotel", ["sem_reserva_hotel"], ["com_reserva_hotel"], ["sem_reserva_hotel"]),
    Acao("fazer_malas", ["malas_desfeitas"], ["malas_prontas"], ["malas_desfeitas"]),
    Acao("viajar_para_disney", ["com_passagens", "com_visto", "malas_prontas", "com_reserva_hotel", "em_casa"],
         ["na_disney"], ["em_casa"]),
]

estado_inicial_disney = set([
    "sem_passaporte",
    "sem_visto",
    "sem_passagens",
    "sem_reserva_hotel",
    "malas_desfeitas",
    "em_casa"
])

objetivo_disney = set(["na_disney"])

def strips_regressivo(estado_inicial, objetivo, acoes):
    plano = []
    objetivos = objetivo.copy()
    memoria_trabalho = estado_inicial.copy()

    while objetivos:
        objetivo_atual = objetivos.pop()

        if objetivo_atual in memoria_trabalho:
            continue

        encontrada = False
        for acao in acoes:
            if objetivo_atual in acao.add:
                encontrada = True
                plano.insert(0, acao)

                objetivos.update(acao.preconds - memoria_trabalho)

                memoria_trabalho.update(acao.add)
                memoria_trabalho.difference_update(acao.delete)
                break

        if not encontrada:
            raise Exception(f"Nenhuma ação encontrada para o objetivo '{objetivo_atual}'")

    return plano


try:
    plano_disney = strips_regressivo(estado_inicial_disney, objetivo_disney, acoes_disney)
    print("Plano gerado:")
    for passo, acao in enumerate(plano_disney, 1):
        print(f"Passo {passo}: {acao}")
except Exception as e:
    print(f"Erro ao gerar plano: {e}")